name: Generate a build and push to branch "Build"

on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - .prettierrc.json
      - '**.md'
      - '**.lock'
      - .prettierignore
      - .gitattributes
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build-frontend # Build project

      # Deploy Ssh
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_HOSTING_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      
      - name: Adding Known Hosts
          run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        
      - name: Deploy with rsync
          run: rsync -avz -e "ssh -p ${{ secrets.SSH_PORT }}" frontend/dist ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:apexi.tech/war/

      - name: Push to build tree
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: frontend/dist
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: 'Build: ({sha}) {msg}' # The commit message
